### ISSUE TITLE
复现结果失败

### ISSUE THREAD

**Issue by Teassassin** [MIRALab-USTC/GNN-LMC#1]
作者您好！感谢您扎实的工作！

我在尝试复现结果时遇到了问题，详细如下：

-----

**操作步骤**

1. 配置好Python环境
2. `cd` 到代码目录
3. 执行 `python setup.py install`
4. 执行 `CUDA_VISIBLE_DEVICES=0 python main_large.py dataset=arxiv  model=gcn  model.json='./json/gcn/arxiv/variant.json'`

-----

**报错信息**

```
Traceback (most recent call last):
  File "main_large.py", line 13, in <module>
    from pyg_autoscale import (get_data, metis, random_subgraph, permute,
  File "/home/tkk-20/WorkDir/Codes/GNN-LMC/pyg_autoscale/__init__.py", line 10, in <module>
    library, [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'
```

-----

**运行环境**

操作系统：WSL-Ubuntu-20.04

CUDA环境：
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

Python环境：
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
antlr4-python3-runtime    4.8                      pypi_0    pypi
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2022.12.7        py37h06a4308_0    defaults
charset-normalizer        3.1.0                    pypi_0    pypi
dgl-autoscale             0.0.0                    pypi_0    pypi
googledrivedownloader     0.4                      pypi_0    pypi
hydra-core                1.1.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        4.13.0                   pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
isodate                   0.6.1                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
littleutils               0.2.2                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
networkx                  2.6.3                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
ogb                       1.3.3                    pypi_0    pypi
omegaconf                 2.1.2                    pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0    defaults
outdated                  0.2.2                    pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pip                       22.3.1           py37h06a4308_0    defaults
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.7.16               h7a1cb2a_0    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python-louvain            0.16                     pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
rdflib                    6.3.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
requests                  2.28.2                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                65.6.3           py37h06a4308_0    defaults
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.1               h5eee18b_0    defaults
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
torch                     1.9.0+cu111              pypi_0    pypi
torch-cluster             1.5.9                    pypi_0    pypi
torch-geometric           1.7.2                    pypi_0    pypi
torch-scatter             2.0.7                    pypi_0    pypi
torch-sparse              0.6.10                   pypi_0    pypi
torch-spline-conv         1.2.1                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0    defaults
xz                        5.2.10               h5eee18b_1    defaults
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults
```

-----
如能解答，将不胜感激！

**Comment by wjie98** [comment]
Hello, you may have already solved this problem. To facilitate others, let me explain my solution:
```bash
# just run
python setup.py build_ext --inplace
```
This method can put the compiled dynamic link library into the pyg_autoscale subdirectory of the source code directory. The dgl_autoscale installed with "python setup.py install" contains three files: _async.so, _relabel2hop.so, and _relabel.so. Because the directory they are located in is not in Python's library search path, they cannot be loaded. This can be fixed by using the aforementioned code.

**Comment by Teassassin** [comment]
> Hello, you may have already solved this problem. To facilitate others, let me explain my solution:
> 
> ```shell
> # just run
> python setup.py build_ext --inplace
> ```
> 
> This method can put the compiled dynamic link library into the pyg_autoscale subdirectory of the source code directory. The dgl_autoscale installed with "python setup.py install" contains three files: _async.so, _relabel2hop.so, and _relabel.so. Because the directory they are located in is not in Python's library search path, they cannot be loaded. This can be fixed by using the aforementioned code.

It works! Thank you so much for your reply!
